# Generated by Django 3.0.6 on 2020-06-05 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loyalty_card',
            field=models.ForeignKey(default=6, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.LoyaltyCard'),
        ),
    ]
