# Generated by Django 3.0.6 on 2020-06-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.ImageField(default='product_default.jpg', upload_to='product_pics')),
            ],
        ),
    ]
