# Generated by Django 3.1.1 on 2020-09-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_feature_featureset_featurevariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Множественный выбор'), ('radiobutton', 'Одиночный выбор')], default='checkbox', max_length=11),
        ),
    ]
